using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Flamoris.Studio.Server.Data.Migrations;

[DbContext(typeof(StudioDbContext))]
[Migration("20260923000000_InitialStudio")]
public sealed class InitialStudio : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE "AspNetUsers" (
              "Id" text PRIMARY KEY, "UserName" varchar(256), "NormalizedUserName" varchar(256),
              "Email" varchar(256), "NormalizedEmail" varchar(256), "EmailConfirmed" boolean NOT NULL,
              "PasswordHash" text, "SecurityStamp" text, "ConcurrencyStamp" text,
              "PhoneNumber" text, "PhoneNumberConfirmed" boolean NOT NULL,
              "TwoFactorEnabled" boolean NOT NULL, "LockoutEnd" timestamptz,
              "LockoutEnabled" boolean NOT NULL, "AccessFailedCount" integer NOT NULL
            );
            CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
            CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
            CREATE TABLE "AspNetRoles" (
              "Id" text PRIMARY KEY, "Name" varchar(256), "NormalizedName" varchar(256), "ConcurrencyStamp" text
            );
            CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
            CREATE TABLE "AspNetUserClaims" (
              "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              "UserId" text NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
              "ClaimType" text, "ClaimValue" text
            );
            CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims"("UserId");
            CREATE TABLE "AspNetUserLogins" (
              "LoginProvider" text NOT NULL, "ProviderKey" text NOT NULL, "ProviderDisplayName" text,
              "UserId" text NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
              PRIMARY KEY ("LoginProvider", "ProviderKey")
            );
            CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins"("UserId");
            CREATE TABLE "AspNetUserRoles" (
              "UserId" text NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
              "RoleId" text NOT NULL REFERENCES "AspNetRoles"("Id") ON DELETE CASCADE,
              PRIMARY KEY ("UserId", "RoleId")
            );
            CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles"("RoleId");
            CREATE TABLE "AspNetUserTokens" (
              "UserId" text NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
              "LoginProvider" text NOT NULL, "Name" text NOT NULL, "Value" text,
              PRIMARY KEY ("UserId", "LoginProvider", "Name")
            );
            CREATE TABLE "AspNetRoleClaims" (
              "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              "RoleId" text NOT NULL REFERENCES "AspNetRoles"("Id") ON DELETE CASCADE,
              "ClaimType" text, "ClaimValue" text
            );
            CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims"("RoleId");
            CREATE TABLE executions (
              "Id" uuid PRIMARY KEY, "UserId" text NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
              "Source" text NOT NULL, "Category" text NOT NULL, "Operation" text NOT NULL,
              "Workflow" text NOT NULL, "UpstreamJobId" text, "RequestSnapshot" jsonb NOT NULL,
              "LastKnownStatus" text NOT NULL, "SubmittedAt" timestamptz NOT NULL,
              "StartedAt" timestamptz, "CompletedAt" timestamptz,
              "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz NOT NULL
            );
            CREATE INDEX "IX_executions_UserId_CreatedAt" ON executions ("UserId", "CreatedAt");
            CREATE INDEX "IX_executions_UpstreamJobId" ON executions ("UpstreamJobId");
            CREATE TABLE assets (
              "Id" uuid PRIMARY KEY, "UserId" text NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
              "ExecutionId" uuid NOT NULL REFERENCES executions("Id") ON DELETE CASCADE,
              "Source" text NOT NULL, "UpstreamAssetId" text NOT NULL,
              "StorageProvider" text NOT NULL, "StorageLocator" text NOT NULL, "StoragePath" text,
              "OriginalFilename" text, "DisplayName" text NOT NULL, "MediaKind" text NOT NULL,
              "MimeType" text NOT NULL, "SizeBytes" bigint, "Width" integer, "Height" integer,
              "Checksum" text, "ThumbnailLocator" text, "Availability" text NOT NULL,
              "CreatedAt" timestamptz NOT NULL, "UpdatedAt" timestamptz NOT NULL, "Metadata" jsonb NOT NULL
            );
            CREATE INDEX "IX_assets_UserId_ExecutionId" ON assets ("UserId", "ExecutionId");
            CREATE UNIQUE INDEX "IX_assets_ExecutionId_UpstreamAssetId" ON assets ("ExecutionId", "UpstreamAssetId");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql("""
            DROP TABLE assets; DROP TABLE executions;
            DROP TABLE "AspNetRoleClaims"; DROP TABLE "AspNetUserTokens";
            DROP TABLE "AspNetUserRoles"; DROP TABLE "AspNetUserLogins";
            DROP TABLE "AspNetUserClaims"; DROP TABLE "AspNetRoles"; DROP TABLE "AspNetUsers";
            """);
}
